"""create tickets table

Revision ID: 6c917e40d7ce
Revises:
Create Date: 2026-09-23 20:55:28.441762

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c917e40d7ce"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "critical", name="ticket_priority"),
            server_default="medium",
            nullable=False,
        ),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String(length=50)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("assigned_to", sa.String(length=320), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(assigned_to IS NULL) = (assigned_at IS NULL)",
            name=op.f("ck_tickets_assignment_consistent"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
    )
    op.create_index(
        "ix_tickets_created_at_id", "tickets", ["created_at", "id"], unique=False
    )
    op.create_index("ix_tickets_priority", "tickets", ["priority"], unique=False)
    op.create_index(
        "ix_tickets_tags", "tickets", ["tags"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tickets_tags", table_name="tickets", postgresql_using="gin")
    op.drop_index("ix_tickets_priority", table_name="tickets")
    op.drop_index("ix_tickets_created_at_id", table_name="tickets")
    op.drop_table("tickets")
    sa.Enum(name="ticket_priority").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
